import type { Component } from "svelte";
import {
  Key,
  Globe,
  AlertTriangle,
  Server,
  FolderCheck,
  MessageSquare,
  Boxes,
  FileText,
  Plug,
  User,
  BookUser,
  Camera,
  Wifi,
  KeyRound,
  Zap,
  ScanLine,
  Star,
  Disc,
  Monitor,
  Mail,
  Settings,
  ClipboardCheck,
  FilePlus,
  MonitorDot,
  Inbox,
  HardDrive,
  Save,
  FileCheck,
  Folder,
  FolderOpen,
  FolderArchive,
  Unlock,
  FileWarning,
  FilePlus2,
  Play,
  TerminalSquare,
  Archive,
  Trash,
  Image,
  Clock,
  Search,
  Spline,
  MemoryStick,
  Trash2,
  StickyNote,
  XCircle,
  HelpCircle,
  Package,
  FileArchive,
  UnlockKeyhole,
  LockKeyhole,
  CheckCircle2,
  PenTool,
  Eye,
  KeySquare,
  Home,
  StarOff,
  Terminal,
  Feather,
  Apple,
  BookMarked,
  DollarSign,
  BadgeCheck,
  Smartphone,
  FolderKey,
} from "@lucide/svelte";

// Lucide-svelte exports each icon as a Svelte component. Use `Component<any>` shape.
export type IconComponent = Component<any, any, any>;

export interface KeePassIcon {
  id: number;
  name: string;
  icon: IconComponent;
  description: string;
}

export const KEEPASS_ICONS: KeePassIcon[] = [
  { id: 0, name: "Key", icon: Key, description: "Key / Password" },
  { id: 1, name: "World", icon: Globe, description: "Network / World" },
  { id: 2, name: "Warning", icon: AlertTriangle, description: "Warning" },
  { id: 3, name: "Server", icon: Server, description: "Server" },
  { id: 4, name: "MarkedDirectory", icon: FolderCheck, description: "Marked Folder" },
  { id: 5, name: "UserCommunication", icon: MessageSquare, description: "Communication" },
  { id: 6, name: "Parts", icon: Boxes, description: "Components / Parts" },
  { id: 7, name: "Notepad", icon: FileText, description: "Notes / Text" },
  { id: 8, name: "Socket", icon: Plug, description: "Socket / Connection" },
  { id: 9, name: "Identity", icon: User, description: "User Identity" },
  { id: 10, name: "AddressBook", icon: BookUser, description: "Address Book" },
  { id: 11, name: "Camera", icon: Camera, description: "Camera / Images" },
  { id: 12, name: "IRCommunication", icon: Wifi, description: "Wireless" },
  { id: 13, name: "Keys", icon: KeyRound, description: "Keyring" },
  { id: 14, name: "Energy", icon: Zap, description: "Energy / Power" },
  { id: 15, name: "Scanner", icon: ScanLine, description: "Scanner" },
  { id: 16, name: "StarYellow", icon: Star, description: "Favorite" },
  { id: 17, name: "CD", icon: Disc, description: "Optical Disc" },
  { id: 18, name: "Monitor", icon: Monitor, description: "Monitor" },
  { id: 19, name: "EMail", icon: Mail, description: "Email" },
  { id: 20, name: "Configuration", icon: Settings, description: "Settings" },
  { id: 21, name: "ClipboardReady", icon: ClipboardCheck, description: "Clipboard Ready" },
  { id: 22, name: "PaperNew", icon: FilePlus, description: "New Document" },
  { id: 23, name: "Screen", icon: MonitorDot, description: "Desktop / Screen" },
  { id: 24, name: "EMailBox", icon: Inbox, description: "Mailbox" },
  { id: 25, name: "Disk", icon: HardDrive, description: "Disk / Drive" },
  { id: 26, name: "Drive", icon: Save, description: "Save / Floppy" },
  { id: 27, name: "PaperReady", icon: FileCheck, description: "Document Ready" },
  { id: 28, name: "Folder", icon: Folder, description: "Folder" },
  { id: 29, name: "FolderOpen", icon: FolderOpen, description: "Open Folder" },
  { id: 30, name: "FolderPackage", icon: FolderArchive, description: "Folder Archive" },
  { id: 31, name: "LockOpen", icon: Unlock, description: "Unlocked" },
  { id: 32, name: "PaperFlag", icon: FileWarning, description: "Document Warning" },
  { id: 33, name: "PaperNew2", icon: FilePlus2, description: "New File (Alt)" },
  { id: 34, name: "Run", icon: Play, description: "Run / Execute" },
  { id: 35, name: "TerminalEncrypted", icon: TerminalSquare, description: "Encrypted Terminal" },
  { id: 36, name: "PaperFlag2", icon: Archive, description: "Archive" },
  { id: 37, name: "Trash", icon: Trash, description: "Trash" },
  { id: 38, name: "TuxImage", icon: Image, description: "Image (Linux/Tux)" },
  { id: 39, name: "Clock", icon: Clock, description: "Clock / Time" },
  { id: 40, name: "SearchInPage", icon: Search, description: "Search" },
  { id: 41, name: "Vector", icon: Spline, description: "Vector Graphics" },
  { id: 42, name: "Memory", icon: MemoryStick, description: "Memory" },
  { id: 43, name: "TrashBin", icon: Trash2, description: "Recycle Bin" },
  { id: 44, name: "Note", icon: StickyNote, description: "Note" },
  { id: 45, name: "Cancel", icon: XCircle, description: "Cancel" },
  { id: 46, name: "Help", icon: HelpCircle, description: "Help" },
  { id: 47, name: "Package", icon: Package, description: "Package" },
  { id: 48, name: "Folder2", icon: Folder, description: "Folder (Alt)" },
  { id: 49, name: "FolderOpen2", icon: FolderOpen, description: "Open Folder (Alt)" },
  { id: 50, name: "TARPackage", icon: FileArchive, description: "TAR Archive" },
  { id: 51, name: "Decrypted", icon: UnlockKeyhole, description: "Decrypted" },
  { id: 52, name: "Encrypted", icon: LockKeyhole, description: "Encrypted" },
  { id: 53, name: "Apply", icon: CheckCircle2, description: "Apply / OK" },
  { id: 54, name: "Signature", icon: PenTool, description: "Signature" },
  { id: 55, name: "Thumbnail", icon: Image, description: "Thumbnail" },
  { id: 56, name: "AddressBook2", icon: BookUser, description: "Address Book (Alt)" },
  { id: 57, name: "View", icon: Eye, description: "View" },
  { id: 58, name: "SecretKey", icon: KeySquare, description: "Secret Key" },
  { id: 59, name: "MultiKeys", icon: FolderKey, description: "Multiple Keys" },
  { id: 60, name: "Home", icon: Home, description: "Home" },
  { id: 61, name: "Star2", icon: StarOff, description: "Unfavorite" },
  { id: 62, name: "Penguin", icon: Terminal, description: "Linux / Terminal" },
  { id: 63, name: "Feather", icon: Feather, description: "Feather" },
  { id: 64, name: "Apple", icon: Apple, description: "Apple / macOS" },
  { id: 65, name: "Wiki", icon: BookMarked, description: "Wiki" },
  { id: 66, name: "Money", icon: DollarSign, description: "Money / Finance" },
  { id: 67, name: "Certificate", icon: BadgeCheck, description: "Certificate" },
  { id: 68, name: "Mobile", icon: Smartphone, description: "Mobile Device" },
];

export function getIconById(id: number): KeePassIcon {
  return KEEPASS_ICONS.find((i) => i.id === id) ?? KEEPASS_ICONS[0];
}

export function getIconComponent(id: number): IconComponent {
  return getIconById(id).icon;
}
